{% set name = "facit" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/facit-{{ version }}.tar.gz
  sha256: 79e3f7b23be454ecc3f559104cab1735c97f3b897c1f9a6c4fa96dcfda0f46c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - jsonpickle
    - openmdao
    - numpy
    - pandas
    - pydantic
    - xarray
    - zarr

test:
  imports:
    - facit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ovidner/facit
  license: MIT
  license_file: LICENSE
  summary: A framework for optimization-based design automation and product configuration

extra:
  recipe-maintainers:
    - ovidner
